site_name: Discord.gd Docs
site_description: "A Godot plugin to interact with the Discord Bot API. Make Discord Bots in Godot!"
site_author: "Delano Lourenco"
repo_url: "https://github.com/3ddelano/discord.gd"
copyright: Copyright &copy; 2022 Delano Lourenco
nav:
  - Home: index.md
  - Installation: installation.md
  - How to Update: how-to-update.md
  - Getting Started: getting-started.md
  - Simple Bot: simple-bot.md
  - Advanced Bot: advanced-bot.md
  - Classes:
      DiscordRESTClient: classes/DiscordRESTClient.md
      Application: classes/Application.md
theme:
  name: "material"
  language: "en"
  favicon: assets/favicon.png
  static_templates:
    - 404.html
  features:
    - navigation.tracking
    - navigation.top
    - navigation.expand
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - header.autohide
  include_search_page: false
  search_index_only: true
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/library
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - css/github-dark.min.css
  - css/extra.css
extra_javascript:
  - js/highlight.min.js
  - js/gdscript.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/extra.js
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/3ddelano
      name: Github
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/c/delanolourenco
      name: Youtube
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - toc:
      title: On this page
      permalink: true
plugins:
  - search:
      separator: '[\s\-\.]'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  # - git-revision-date
  - ezlinks:
      warn_ambiguities: true
      wikilinks: true
